"""Designed marketing pages. Content is based on the supplied Wellenetz pages."""

def build_marketing_pages(page, section, sh, eyebrow, button, a, cases, casecard):
    paths = ['/marketing/support/', '/marketing/small-short-term-insurance/', '/marketing/kinqr/']
    labels = ['マーケティング支援', '事業開発', 'デジタルサービス']

    def navigation(current):
        return '<nav class="mk-nav wrap" aria-label="マーケティング事業の関連ページ">' + a('/marketing/', 'マーケティング事業') + ''.join(f'<a href="{url}"'+(' aria-current="page"' if url==current else '')+f'>{label}</a>' for url,label in zip(paths,labels)) + '</nav>'

    def hero(path, no, en, name, title, desc, visual, theme=''):
        brand_logo = '<div class="mk-official-logo"><img src="/assets/kinqr-logo.png" alt="緊QR（DynQ）公式ロゴ" width="1022" height="584"></div>' if path == paths[2] else ''
        return '<div class="mk-page '+theme+'"><div class="wrap"><nav class="breadcrumbs" aria-label="パンくず">'+a('/','HOME')+'<span>/</span>'+(a('/marketing/','マーケティング事業')+'<span>/</span>' if path!='/marketing/' else '')+'<span>'+name+'</span></nav></div><section class="mk-hero"><div class="wrap mk-hero-grid"><div class="mk-hero-copy">'+eyebrow(no+' / '+en)+'<p class="mk-service-name">'+name+'</p>'+brand_logo+'<h1>'+title+'</h1><p class="mk-lead">'+desc+'</p><div class="actions">'+button('/inquiry/general/','このサービスを相談する','orange')+a('#overview','サービスの内容を知る','mk-anchor')+'</div></div><div class="mk-hero-visual">'+visual+'</div></div><div class="wrap mk-hero-caption"><span>WELLENETZ / MARKETING DIVISION</span><span>'+en+'</span></div></section>'+navigation(path)

    def finish(content):
        return content+'</div>'

    def related(current):
        titles = ['マーケティング支援', '少額短期保険事業参入支援', '緊QR']
        return section(sh('OTHER AREAS','ほかの領域も見る。')+'<div class="mk-related">'+''.join(a(url, '<span class="num">0'+str(i+1)+'</span><div><small>'+labels[i]+'</small><h3>'+titles[i]+'</h3></div><span class="text-link">詳細</span>', 'mk-related-item') for i,url in enumerate(paths) if url!=current)+'</div>', 'soft')

    def steps(items):
        return '<ol class="mk-steps">'+''.join('<li><span class="mk-step-number">'+f'{i+1:02}'+'</span><div>'+('<span class="mk-owner">'+owner+'</span>' if owner else '')+'<h3>'+title+'</h3><p>'+desc+'</p></div></li>' for i,(title,desc,owner) in enumerate(items))+'</ol>'

    def tiles(items):
        return '<div class="mk-tiles">'+''.join('<article><span class="num">'+f'{i+1:02}'+'</span><h3>'+title+'</h3><p>'+desc+'</p></article>' for i,(title,desc) in enumerate(items))+'</div>'

    # Marketing overview retains the user-approved hierarchy.
    overview=hero('/marketing/','00','MARKETING','マーケティング事業','「惹き寄せる」から、<br><em>事業をつくる</em>まで。','顧客との接点をつくる。選ばれる理由をつくる。<br>そして、新しい事業そのものをつくる。企業の可能性を、3つの領域からひらきます。','<div class="mk-area-map"><div class="mk-map-top"><span>STARTING POINT</span><strong>企業が持つ価値・強み</strong></div><div class="mk-map-branches">'+''.join('<div><span>0'+str(i+1)+'</span><strong>'+t+'</strong><small>'+s+'</small></div>' for i,(t,s) in enumerate([('マーケティング支援','顧客を惹き寄せる'),('事業開発','新しい事業をつくる'),('デジタルサービス','仕組みで解決する')]))+'</div></div>')
    entries=[('01','MARKETING SUPPORT','マーケティング支援','売り込むのではなく、<br>「知りたい」をつくる。','WEB、コンテンツ、動画、SNS。それぞれの施策を、ひとつの「選ばれる理由」でつなぐ。顧客が自分から興味を持ち、相談したくなる接点を設計します。','詳細',['価値の言語化','接点の設計','実行・改善']),('02','BUSINESS DEVELOPMENT','事業開発','本業の強みを、<br>次の事業の種に。','既存の商品・サービス、顧客基盤、業界知識。その企業だからこそ持っている資産と顧客の課題を結びつけ、新しい事業の原型をつくります。','少額短期保険事業参入支援',['顧客インサイト','事業コンセプト','ブランド設計']),('03','DIGITAL SERVICE','デジタルサービス','課題を、<br>使える仕組みで解決する。','企業や自治体が抱える課題を、デジタルの仕組みへ。第一弾の「緊QR」は、平時の情報案内と緊急時の情報提供を、同じQRコードでつなぎます。','緊QR',['日常の案内','緊急時の情報','運用支援'])]
    overview+=section(sh('THREE BUSINESS AREAS','マーケティング事業の3領域。')+'<div class="mk-area-list">'+''.join('<article class="mk-area-entry"><div class="mk-area-title"><span class="mk-large-number">'+no+'</span>'+eyebrow(en)+'<h3>'+title+'</h3></div><div><h4>'+catch+'</h4><p>'+desc+'</p><div class="mk-tags">'+''.join('<span>'+tag+'</span>' for tag in tags)+'</div>'+button(url,link,'outline')+'</div></article>' for url,(no,en,title,catch,desc,link,tags) in zip(paths,entries))+'</div>',id='overview')
    overview+=section('<div class="split"><div>'+eyebrow('OUR STARTING POINT')+'<h2>何をするかの前に、<br>なぜ選ばれるか。</h2></div><div><p>施策やサービスが変わっても、出発点は同じです。顧客を理解し、自社の価値を見つけ、必要な人に伝わる言葉と接点へ。</p><p>ベレネッツはブランディングとマーケティングを一体で考え、実行までつなぎます。</p></div></div>','dark')
    page('/marketing/','マーケティング事業',finish(overview),hero=False,lead='マーケティング支援、事業開発、デジタルサービス。企業の価値を、次の成長につなぐ3つの領域。')

    # 01 — customer journey, practical service directory, and process.
    visual='<div class="mk-journey"><div class="mk-diagram-label">CUSTOMER JOURNEY</div><p>「選ばれる理由」を、<br>顧客の行動につなぐ。</p><ol>'+''.join('<li><span>'+f'{i+1:02}'+'</span><div><strong>'+t+'</strong><small>'+d+'</small></div></li>' for i,(t,d) in enumerate([('気づく','自分の課題と出会う'),('知りたくなる','価値と違いを理解する'),('相談したくなる','次の行動を、自分から')]))+'</ol><div class="mk-diagram-foot">VALUE → MESSAGE → ACTION</div></div>'
    content=hero(paths[0],'01','MARKETING SUPPORT','マーケティング支援','売り込むのではなく、<br><em>「知りたい」</em>をつくる。','企業の価値を見つけ、顧客に伝わる言葉へ。<br>必要な施策をつなぎ、顧客が自分から動き出す仕組みをつくります。',visual)
    content+=section('<div class="mk-section-intro"><div>'+eyebrow('VALUE BEFORE TACTICS')+'<h2>いきなり「集客」から、<br>始めない。</h2></div><p>アクセスや広告を増やす前に、まず「なぜ選ばれるのか」を明確に。顧客の理解と企業の価値を、マーケティングの土台にします。</p></div>'+tiles([('顧客を知る','誰に選ばれたいのか。その人は何に困り、どんな情報を求めているのか。'),('価値を見つける','強み、技術、実績、顧客との関係。まだ十分に伝わっていない価値を探します。'),('選ばれる理由をつくる','競合との違いを、顧客の言葉に。すべての施策の中心になるメッセージを設計します。')]),id='overview')
    content+=section('<div class="mk-section-intro"><div>'+eyebrow('NON-ADVERTISING MARKETING')+'<h2>納得が、<br>次の行動をつくる。</h2></div><div><p>顧客が「これは自分に必要かもしれない」と気づき、興味を持ち、調べ、相談したくなる。私たちはこの考え方を「非広告型マーケティング」と呼んでいます。</p><p>広告を使う場合も、ブランド・WEB・コンテンツと連動させ、顧客の自然な理解を支えます。</p></div></div><div class="mk-channel-band"><strong>ひとつの<br>選ばれる理由</strong><div>'+''.join('<span>'+t+'</span>' for t in ['WEBサイト','検索・SEO','オウンドメディア','動画','SNS','メール・LINE','広告','営業資料'])+'</div></div>','dark')
    serviceitems=[('WEB / SEO','ホームページ構築・運用','企業の理解と相談につながる営業拠点へ。','サイト構造、コンテンツ、SEO、導線を一体で設計。公開後の改善・運用まで支援します。'),('OWNED MEDIA','オウンドメディア構築・運用','専門知識を、顧客との継続的な接点へ。','検索される疑問や課題に答えるコンテンツを届け、記事を通じて理解と信頼を積み重ねます。'),('LANDING PAGE','LPマーケティング','「なぜ必要か」が伝わる構成に。','商品説明だけでなく、必要性と選ばれる理由を伝えるLPを企画・制作し、改善まで対応します。'),('WRITING','ライティング','商品の説明を、顧客にとっての価値へ。','WEB、記事、広告、営業資料まで、顧客との接点で使う言葉を設計します。'),('ADVERTISING','ネット広告運用','必要な顧客との出会いをつくる。','Google広告やSNS広告を、LP・WEBサイト・ブランドメッセージと連動させて運用します。'),('MAIL / LINE','メルマガ・LINEマーケティング','一度の接点を、続く関係へ。','メルマガやステップメール、LINEによる継続的な情報提供で、潜在顧客との関係を育てます。'),('MOVIE','動画マーケティング','技術や人物、ストーリーを映像で。','YouTube、ショート動画、AIを活用した動画など、目的に合わせたコンテンツを設計します。'),('RECRUITMENT','採用マーケティング','「ここで働く理由」を届ける。','企業文化、仕事の意味、社員のストーリーを伝え、まだ転職活動を始めていない層との接点もつくります。')]
    content+=section(sh('MARKETING SERVICES','必要な施策を、必要な組み合わせで。','<p>すべてを実施する必要はありません。<br>課題・顧客・商材・営業方法に合わせて選びます。</p>')+'<div class="mk-service-grid">'+''.join('<details class="mk-service-detail"><summary><span class="num">'+f'{i+1:02}'+'</span><span><small>'+en+'</small><strong>'+title+'</strong><span class="mk-service-summary">'+desc+'</span></span></summary><p>'+detail+'</p></details>' for i,(en,title,desc,detail) in enumerate(serviceitems))+'</div>','soft')
    content+=section(sh('HOW WE WORK','選ばれる構造を、実行へ。')+steps([('顧客を理解する','選ばれたい顧客、抱える課題、知りたい情報を整理します。',''),('自社の価値を整理する','強み・実績・技術・顧客評価から、選ばれる理由を抽出します。',''),('伝える内容と導線を設計する','知る、興味を持つ、理解する、比較する、相談する。その流れを設計します。',''),('必要な施策を実行する','WEB、コンテンツ、広告、動画、メールなどを組み合わせます。','')]))
    content+=section('<div class="mk-ai-panel"><div class="mk-ai-label">AI <span>×</span><br>MARKETING</div><div>'+eyebrow('HUMAN INSIGHT, AMPLIFIED')+'<h2>AIにも、企業の独自性を。</h2><p>顧客理解、競合分析、企画、制作、改善にAIを活用。その企業にしかない情報・経験・価値を起点に、マーケティングへ落とし込みます。</p></div></div>','soft')
    content+=section(sh('RELATED CASES','価値が届くと、事業が動く。',a('/case_study/','すべての事例','text-link'))+'<div class="grid3">'+''.join(casecard(c) for c in cases[:3])+'</div>')+related(paths[0])
    page(paths[0],'マーケティング支援',finish(content),hero=False,lead='ブランディングを起点に、WEB・コンテンツ・広告・動画をつなぐマーケティング支援。')

    # 02 — brand-first business design and a clear division of responsibilities.
    visual='<div class="mk-business-diagram"><div class="mk-diagram-label">BUSINESS DESIGN</div><div class="mk-business-inputs"><span>自社の強み</span><b>×</b><span>顧客の課題</span></div><div class="mk-business-core"><small>WELLENETZ</small><strong>選ばれる<br>事業コンセプト</strong><span>顧客価値 / 競争優位性 / ブランド</span></div><div class="mk-business-output"><span>専門会社と連携</span><strong>保険商品・制度設計、会社設立へ</strong></div></div>'
    content=hero(paths[1],'02','BUSINESS DEVELOPMENT','少額短期保険事業参入支援','保険会社をつくる前に、<br><em>選ばれる理由</em>をつくる。','貴社の強みと顧客の課題から、新しい保険事業を構想。<br>事業・ブランド設計と会社設立の専門性をつなぎ、参入を支援します。',visual,'mk-business')
    content+=section('<div class="mk-section-intro"><div>'+eyebrow('BRAND FIRST')+'<h2>ブランドを、<br>事業の最初につくる。</h2></div><p>なぜ自社が保険事業を行うのか。誰の、どんな課題を解決するのか。商品や制度を考える前に、事業の意味を明確にします。</p></div><div class="mk-priority"><div><span>01 / DISCOVER</span><h3>顧客と自社を知る</h3><p>顧客インサイト、強み、業界の課題を整理。</p></div><div><span>02 / DEFINE</span><h3>選ばれる理由をつくる</h3><p>価値提案、差別化、事業コンセプトを設計。</p></div><div><span>03 / DEVELOP</span><h3>事業を具体化する</h3><p>ブランドを軸に、保険商品・制度・会社設立へ。</p></div></div>',id='overview')
    content+=section(sh('BUSINESS OPPORTUNITIES','本業の強みを、次の可能性へ。')+tiles([('顧客との関係を深く','保険を通じて、商品やサービスの提供後も続く顧客接点を考えます。'),('新しい事業の柱に','既存の顧客基盤や業界知識を活かした、収益モデルを検討します。'),('提供する価値を広げる','商品・サービスと補償を組み合わせ、本業の競争力につなげます。'),('競合との差をつくる','価格やスペックだけではない、自社が選ばれる理由を設計します。')]),'soft')
    content+=section(sh('TWO EXPERTISES','2つの専門性で、構想から設立へ。')+'<div class="mk-partners"><article class="mk-partner"><span class="mk-partner-role">事業・ブランド設計</span><div class="mk-partner-name">WELLENETZ</div><h3>なぜ選ばれるかを、つくる。</h3><p>株式会社ベレネッツ</p><ul>'+''.join('<li>'+t+'</li>' for t in ['経営意図・事業目的の整理','顧客インサイト・ペルソナ設計','顧客課題・価値提案の明確化','競争優位性・差別化','事業コンセプト・ブランド設計'])+'</ul></article><article class="mk-partner"><span class="mk-partner-role">保険会社設立の専門支援</span><div class="mk-partner-name">REIMAGINE<br>CONSULTING</div><h3>どう成立させるかを、つくる。</h3><p>リイマジンコンサルティング株式会社</p><ul>'+''.join('<li>'+t+'</li>' for t in ['保険商品デザイン・制度設計','概算収支設計・事業方法書','約款・数理関連書類','登録申請・当局への相談対応','保険業務システム・運営体制'])+'</ul></article></div>')
    content+=section(sh('PROJECT ROADMAP','事業の種から、参入まで。')+steps([('事業の種を探す','商品、サービス、顧客、技術、業界知識から、保険事業の可能性を探ります。','ベレネッツ'),('顧客の課題を見つける','誰が何に困り、既存の商品や保険でなぜ解決されていないのかを整理します。','ベレネッツ'),('選ばれる理由をつくる','誰に、何を、なぜ自社が提供するのか。コンセプトとブランドを設計します。','ベレネッツ'),('保険商品・制度へ落とし込む','事業構想を、実際に成立する保険商品・制度として具体化します。','リイマジンコンサルティング'),('会社設立・登録を進める','必要書類、登録申請、当局対応、システム、運営体制を整備します。','リイマジンコンサルティング')]),'soft')
    content+=section('<div class="split"><div>'+eyebrow('IS THIS FOR YOU?')+'<h2>「保険事業の種」は、<br>すでにあるかもしれません。</h2><p>具体的な保険商品が決まっていなくても、<br>可能性を考える段階からご相談いただけます。</p></div><ul class="mk-check-list">'+''.join('<li>'+t+'</li>' for t in ['多くの顧客・会員・取引先を持っている','独自の商品やサービスがある','業界特有の課題をよく知っている','新しい事業の柱を探している','価格以外の差別化をつくりたい'])+'</ul></div>','dark')+related(paths[1])
    page(paths[1],'少額短期保険事業参入支援',finish(content),hero=False,lead='事業コンセプト・顧客価値・ブランドを設計し、専門会社と連携して少額短期保険事業への参入を支援します。')

    # 03 — clearly labelled conceptual state switch; no pretend emergency data.
    visual='<div class="mk-qr-diagram" data-qr-demo><div class="mk-diagram-label">情報の切り替えイメージ</div><div class="mk-qr-origin"><span>ひとつのQRコード</span><strong>貼り替えずに、<br>届ける情報を変える。</strong></div><div class="mk-qr-switch" role="group" aria-label="情報の切り替えイメージ"><button type="button" data-qr-mode="normal" aria-pressed="true">平時</button><button type="button" data-qr-mode="emergency" aria-pressed="false">緊急時</button></div><div class="mk-qr-state" data-qr-panel="normal"><small>NORMAL / 情報QR</small><h2>施設を、もっと便利に。</h2><ul><li>施設案内・アクセス</li><li>観光・多言語情報</li><li>自治体からのお知らせ</li></ul></div><div class="mk-qr-state emergency" data-qr-panel="emergency" hidden><small>EMERGENCY / 緊QR</small><h2>いざという時の情報へ。</h2><ul><li>災害情報・避難情報</li><li>緊急のお知らせ</li><li>避難先への案内</li></ul></div><p class="mk-qr-status" aria-live="polite" data-qr-status>平時の情報提供を表示しています。</p></div>'
    content=hero(paths[2],'03','DIGITAL SERVICE','緊急時情報管理サービス「緊QR」','平時は案内。<br>緊急時は、<em>避難情報へ。</em>','普段から使う情報の接点を、いざという時にも。<br>同じQRコードから、状況に応じて必要な情報を届けます。',visual,'mk-kinqr')
    content+=section('<div class="mk-section-intro"><div>'+eyebrow('ONE QR, TWO ROLES')+'<h2>QRコードは、そのまま。<br>役割は、状況に合わせて。</h2></div><p>緊QRは、可変QRコード管理基盤「DynQ」を活用した緊急時情報管理サービス。設置済みのQRコードを貼り替えず、情報を切り替えられます。</p></div><div class="mk-mode-cards"><article><span class="mk-mode-label">NORMAL / 日常</span><h3>普段から、役に立つ。</h3><p>施設案内やアクセス、観光情報、多言語案内。日常的に使う情報の入り口として、更新しながら活用します。</p><div class="mk-tags"><span>施設案内</span><span>アクセス</span><span>観光・多言語</span></div></article><article><span class="mk-mode-label">EMERGENCY / 非常時</span><h3>必要な情報へ、つなぐ。</h3><p>災害情報、避難情報、緊急のお知らせ。いつもそこにあるQRコードを、緊急時の情報経路として活用します。</p><div class="mk-tags"><span>災害情報</span><span>避難情報</span><span>緊急案内</span></div></article></div><p class="mk-small-note">利用者は専用アプリをインストールせず、スマートフォンでQRコードを読み取ってアクセスできます。</p>',id='overview')
    content+=section('<div class="split"><div>'+eyebrow('ANOTHER INFORMATION ROUTE')+'<h2>街に、もうひとつの<br>情報経路を。</h2></div><div><p>防災アプリや防災無線に加えて、看板・掲示板・施設・避難所などの「物理的な接点」に、情報の入り口を増やす。</p><p>普段から使う仕組みだからこそ、非常時の接点としても活かせます。</p></div></div>','dark')
    content+=section(sh('WHERE TO USE','いつもの場所を、情報の接点に。')+tiles([('自治体','避難所、公共施設、街頭案内、地域防災など。'),('公共施設','庁舎、文化施設、スポーツ施設の日常案内と緊急情報。'),('大規模施設','オフィスビルや複合施設の館内情報と、災害時の誘導。'),('観光・レジャー施設','平時の観光案内と、非常時の避難情報。')]))
    content+=section(sh('START SMALL','小さく試し、確かめて、広げる。','<p>防災に関わる仕組みだからこそ、<br>実際の環境で確認しながら導入します。</p>')+steps([('ご相談・ヒアリング','導入目的、対象施設、設置場所、現在の情報提供方法を確認します。',''),('導入計画・設置設計','設置場所、平時・緊急時の情報、避難先などを設計します。',''),('実証・導入テスト','一部の施設やエリアで、読み取り・情報切替・避難誘導を確認します。',''),('本導入','検証結果を踏まえ、対象エリアや施設へ展開します。',''),('運用・定期確認','運用確認や訓練を通じ、緊急時に使える状態を維持します。','')]),'soft')
    content+=section('<div class="mk-section-intro"><div>'+eyebrow('SERVICE & SUPPORT')+'<h2>相談から運用まで、<br>ベレネッツが窓口に。</h2></div><div><p>提案・見積、現場調査、設置計画、QR媒体の制作・設置、契約、運用支援、一次サポートまで対応します。</p><p>システムの開発・改修・保守は技術開発側と連携。認定販売パートナーを通じた提供でも、サービス提供主体はベレネッツです。</p></div></div><div class="mk-tags"><span>導入相談</span><span>設置計画</span><span>QR媒体制作</span><span>運用支援</span><span>一次サポート</span></div>')+related(paths[2])
    page(paths[2],'緊急時情報管理サービス「緊QR」',finish(content),hero=False,lead='平時は施設案内、緊急時は避難情報へ。設置したQRコードを貼り替えず、届ける情報を切り替える緊QR。')
